### ISSUE TITLE
Functional components are not hot reloaded

### ISSUE THREAD

**Issue by colinmeinke** [colinmeinke/universal-js#13]
Waiting for solution from [babel plugin react transform](https://github.com/gaearon/babel-plugin-react-transform/issues/57)

**Comment by felixsanz** [comment]
Does this really fixed anything? I can't see a difference

**Comment by gaearon** [comment]
React Hot Loader 3 supports functional components without destroying the state.
It supersedes both React Hot Loader and React Transform, and is built on lessons learned from both.
Check it out: https://github.com/gaearon/react-hot-boilerplate/pull/61
