### ISSUE TITLE
onChangeWithDebounce not working properly in my local build

### ISSUE THREAD

**Issue by cluk3** [colinmeinke/universal-js#17]
I built and started the repo on my pc, everything works fine, except for the name edit, it isn't firing the `UPDATE_NAME` action.
I found out it caused by the `e.target.value` closure into the `onChangeWithDebounce` function 
( ./src/common/components/input/index.js ), the console in the browser actually give me this error:

> Uncaught TypeError: Cannot read property 'value' of null

I was able to solve the problem modifying the function:
```
const onChangeWithDebounce = e => {
    clearTimeout( debounce );
    const inputValue = e.target.value;
    debounce = setTimeout(() => {
      onChange( inputValue );
    }, 500 );
  };
```
I don't know why, but it works now.

**Comment by colinmeinke** [comment]
Hi Luca, thanks for checking out UniversalJS and taking the time to file and issue :smile:

I'm trying to recreate this. What's your setup – OS, browser? Did you build and run in development mode with `npm run build:dev` and `npm run start:dev`, or in production mode `npm run build:pro` and `npm run start:pro`?

**Comment by cluk3** [comment]
hi Colin! i'm running it on Linux Mint 17 and google chrome 47 in dev mode

**Comment by colinmeinke** [comment]
Ah, I have managed to recreate by upgrading React from 0.14.6 to to 0.14.7. React's *synthetic event system* was changed a bit – there is a related issue open on react https://github.com/facebook/react/issues/5939. It turns out React has something called [event pooling](https://facebook.github.io/react/docs/events.html#event-pooling) and re-uses events. Your solution is exactly how to get around this! Will update. Thanks again!

**Comment by colinmeinke** [comment]
Closed by c1c0dbaea1b2c2faeb95a851ad12ed5d495761ab

**Comment by cluk3** [comment]
Thanks Colin, it is always nice to learn something new! Anyway, can i ask you why you are updating the name onChange instead of onSubmit? You can actually update it without pressing the Save button and it is pretty confusing. If you want to keep the behavior of the app like that it would be better to name the button "Done" instead of "Save". My two cents ;) Wonderful work anyway, i think i will copy some of your code for my next projects!

**Comment by colinmeinke** [comment]
Great, I'm glad this has been of some use. You're totally right, done is way better!
