### ISSUE TITLE
Hot reload page component

### ISSUE THREAD

**Issue by colinmeinke** [colinmeinke/universal-js#18]
Currently is only rendered server-side so does not get hot reloaded.

**Comment by felixsanz** [comment]
Any progress on this? Also, i don't know how to make hot reloading work but no matter what i change (even components), webpack is not rebuilding anything

**Comment by colinmeinke** [comment]
Overhauling hot reloading is definitely on my radar. Probably as Dan mentions here https://github.com/colinmeinke/universal-js/issues/19

I am kind of holding off as HMR seems to be in flux at the moment, so was hoping someone comes up with the **one true way** of doing it.

You're correct though, HRM on this project seems to be temperamental, and often will not work. I have filed a bug about it where I think it is originating https://github.com/webpack/webpack-dev-middleware/issues/68, but no response as of yet.

This specific issue is about reloading the `Page` component. This is particularly tricky as it is *only* rendered server side.

**Comment by felixsanz** [comment]
But why hot reloading doesn't work in any way?

And your readme says:

Demonstrates
...
Hot module reloading

So... i'm sorry but i still don't understand why the entire hot reloading thing is not working xD

Not even randomly. If it helps:

```
 npm run start:dev

> universal-js@0.0.1 start:dev .../Desktop/universal
> NODE_ENV=development node ./dist/server.js

Server listening...
webpack built 58a364cf8cc4da7ff57e in 3164ms
```

And thats all

**Comment by felixsanz** [comment]
Not sure if this is related, but my page have this tag:

<script type="text/javascript" charset="utf-8" src="/dist/0.96c731eaf327df44fc32.hot-update.js"></script>

I think thats appended automatically by `entry: 'webpack-hot-middleware/client',`.

The thing is, that js file (hot-update.js), if i try to open it, i get Internal Server Error
