### ISSUE TITLE
Hot reload Redux actions

### ISSUE THREAD

**Issue by colinmeinke** [colinmeinke/universal-js#19]

**Comment by colinmeinke** [comment]
Reliant upon https://github.com/gaearon/babel-plugin-react-transform/issues/26

**Comment by gaearon** [comment]
You might be interested in https://github.com/reactjs/redux/pull/1455.

**Comment by gaearon** [comment]
This is fixed in [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61).
It is built with lessons learned from both React Hot Loader and React Transform.
It’s still in alpha but I encourage you to [check it out](https://github.com/gaearon/react-hot-boilerplate/pull/61)!

**Comment by colinmeinke** [comment]
Thanks Dan!

I've got it partially working https://github.com/colinmeinke/universal-js/commit/44780517e1dede42f2b97ced3cdf04ea9a0e2f5e

However updating actions or reducers hits me with the following error:

```
Uncaught TypeError: Cannot read property 'hot' of undefined

  getAffectedStuff @ client.js:351
  hotApply @ client.js:386
  (anonymous function) @ only-dev-server.js:32
  hotUpdateDownloaded @ client.js:312
  hotAddUpdateChunk @ client.js:284
  webpackHotUpdateCallback @ client.js:5
  (anonymous function) @ 0.4221176….hot-update.js:1
```

**Comment by gaearon** [comment]
Please file this with Webpack, it's an issue on their side. Might be possible to solve by updating it.

**Comment by colinmeinke** [comment]
Issue filed with Webpack https://github.com/webpack/webpack/issues/2387

**Comment by gaearon** [comment]
I think it’s worth adding a stack trace there to make it clear why we think it’s a webpack issue.
Even better, a screenshot of the line where it crashes 😉 .

**Comment by colinmeinke** [comment]
Good idea!
