### ISSUE TITLE
React file size

### ISSUE THREAD

**Issue by felixsanz** [colinmeinke/universal-js#21]
Why /static/js/react.min.js is 136kb ? I tried to figure it out but i failed!

Also client.min.js is 45.5Kb when the apps is almost a hello world!

Thanks for the boilerplate btw :)

I closed the issue because the answer is: gzip

**Comment by felixsanz** [comment]
Answer myself: gzip

**Comment by colinmeinke** [comment]
Yep you got it, that is the size of react ungzipped! `client.min.js` gzips down to bout 10kb so not too bad. Probably could be improved though.

Also, probably worth us adding https://www.npmjs.com/package/compression to `server.js` – I can't really think of a situation where you wouldn't want it. What do you think?

**Comment by felixsanz** [comment]
If nginx acts as a proxy server, isn't nginx taking care of the compression itself?

This is more like an opinion i think.
