### ISSUE TITLE
transform-object-rest-spread plugin what for?

### ISSUE THREAD

**Issue by felixsanz** [colinmeinke/universal-js#22]
What is `transform-object-rest-spread` plugin used for?

The plugin does "Compile object rest and spread to ES5", but i don't know why is this useful?

Most browsers support it, whats the use case here?

I'm loving your starter kit, been struggling this boilerplates for a month and yours is brilliant

**Comment by colinmeinke** [comment]
Thanks Felix, glad it's useful!

`transform-object-rest-spread` adds support for this https://github.com/sebmarkbage/ecmascript-rest-spread

```js
let { x, y, ...z } = { x: 1, y: 2, a: 3, b: 4 };
x; // 1
y; // 2
z; // { a: 3, b: 4 }
```

Pretty sure this isn't commonly supported – chrome at least throws an error when it hits `...`
