### ISSUE TITLE
Feature request: Add relay/graphql

### ISSUE THREAD

**Issue by felixsanz** [colinmeinke/universal-js#24]
Relay is already server-side ready, and provides a way to fetch data that components need, automatically, defining the fragments of data in each component. (As you probably know xD)

Here is a repo example of server-side relay: https://github.com/denvned/isomorphic-relay

Would you consider adding relay/graphql to the boilerplate? It would be awesome!

**Comment by colinmeinke** [comment]
I'd like to keep this boilerplate relatively simple and avoid adding additional features – in an attempt to keep it unintimidating. Plus, I don't use Relay at the moment and this is mainly for me :smile: 

I would only use this library for learning, and create your own boilerplate that can grow with you.
