### ISSUE TITLE
What is that isUpdating thing?

### ISSUE THREAD

**Issue by felixsanz** [colinmeinke/universal-js#25]
isUpdating actions/reducer, what are they for?

**Comment by colinmeinke** [comment]
`isUpdating` is just some state – like normal redux state it has action creators and a reducer to handle updating the store.

This is where the action creators are called – https://github.com/colinmeinke/universal-js/blob/master/src/common/components/Input.js#L12L20

This is the `onChange` event for the form's input, it has a 500ms delay before it dispatches the `updateName` action. The reason for the delay and for `isUpdating` state, is to simulate how we could update our UI to reflect transient state during async events.

`isUpdating` state is used in the button component. If `true` (the case during the 500ms delay) then the button text is set to `Saving`.

**Comment by felixsanz** [comment]
So if i have understand, this is just some state to manage/reflect the usage of an async task, like a loading indicator, right? Safe to remove if not needed. (I was thinking it was part of the redux global workflow)
