### ISSUE TITLE
routing empty module.hot.accept

### ISSUE THREAD

**Issue by felixsanz** [colinmeinke/universal-js#26]
in routes.js, you can see this code:

```javascript
let routes = getRoutes()

if (__DEVELOPMENT__ && module.hot) { // eslint-disable-line no-undef
  module.hot.accept()
  routes = getRoutes()
}
```

1. routes contain the same, it's like a duplication, right?
2. why module.hot.accept() is empty?

_Sorry if asking too much, but this is by far the best boilerplate i've seen (and trust me, i've seen so many), and i would like to understand it 100%, master it, and also being able to contribute with code_

**Comment by colinmeinke** [comment]
As far as I remember:

- `if (__DEVELOPMENT__ && module.hot) {` = if this file has been updated
- `module.hot.accept()` = allow this file to be hot updated
- `routes = getRoutes()` = redefine the routes variable when the file has changed

More here: https://webpack.github.io/docs/hot-module-replacement-with-webpack.html

**Comment by felixsanz** [comment]
But with that logic, it's impossible that it works.
```
if (this file has been updated) {
     allow this file to be hot updated
}
```

You are allowing the file to be updated inside a block that is only executes when the file is updated. Egg/Chicken problem.

I don't get it at all
