### ISSUE TITLE
How the css is integrated in the boilerplate? (question)

### ISSUE THREAD

**Issue by felixsanz** [colinmeinke/universal-js#29]
What this code does?

```
      {
        exclude: /\/Page/,
        loader: 'css-loader?modules',
        test: /\.css$/,
      },
      {
        include: /\/Page/,
        loader: ExtractTextWebpackPlugin.extract(
          'style',
          'css?modules&importLoaders=1!postcss'
        ),
        test: /\.css$/,
      },
```

I can't understand it. Looks like the Page component styles are moved into a .css file? I'm having problems with the CSS because my css at components like <Header> is ignored :/

**Comment by felixsanz** [comment]
Only Page is getting CSS inside style.css. The others components are not! :/

**Comment by colinmeinke** [comment]
This might help you understand it https://github.com/colinmeinke/css-modules-universal-example

**Comment by felixsanz** [comment]
@colinmeinke i've read that 3 times, 2 today before asking and 1 when i discovered your boilerplate hehe. It doesn't help much. i understand the concept but that lines above confuses me.

Looks like all files (except  Page styles) are inlined (without postcss?).
And Page styles are parsed with postcss and moved into styles.css file?

And here is another question: Why i can set a class like `<div className={layout}>` in Layout component **ONLY** in production? In development it doesn't work, no class is rendered

**Comment by felixsanz** [comment]
Also, looks like server is not rendering the classes correctly?

> react.js:19254 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 `(client) reactid="1"><header class="_3n2AZqFntSkY`
` (server) reactid="1"><header data-reactid="2"><di`

Can you help please? I'm sorry if i'm being annoying with random questions :(

**Comment by colinmeinke** [comment]
You're exactly right, Webpack style loader is handling the inline loading of all styles except `Page` at runtime in the browser. `Page` is only part of the server side bundle, therefore we have to serve it externally in `styles.css`.

This in theory should allow Webpack to handle hot reloading CSS also.

This is only in development. In production **all** styles are extracted into `styles.css` so we are not reliant on Javascript.

This is why you are seeing that warning in development, as CSS is being injected client side, therefore server and client don't match. Which is fine to get CSS hot reloading.

However, the [inline styles config of the server file](https://github.com/colinmeinke/universal-js/blob/master/webpack/dev/server.babel.js#L17L21) will never get called. I should probably probably use a noop loader instead.

The part of the Webpack config that is actually relevant when our `client.js` file is run in the browser is in [the development client Webpack config](https://github.com/colinmeinke/universal-js/blob/master/webpack/dev/client.babel.js#L29L32).

Not sure about your `<div className={layout}>` question. Can you provide a full code example. There is no `Layout` component in this project.

**Comment by felixsanz** [comment]
Now it get it. Kinda confusing but thats how webpack work...  ¯\_(ツ)_/¯

The Layout thing, i'm taking a look at your blog to better understand a real world example of the boilerplate. Your blog contains a `<Layout>` component. It doesn't contain styles but if you add a styles.css, a dummy class and then `import { dummyClass } from styles.css` and finally add that class into the Layout component, it doesn't work. But let me take a look again and provide a full example, because i think some other things are also affecting this.

Thanks for the reply
