### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by Noiwex** [colinmeinke/universal-js#36]
He's dead, Jim.

**Comment by colinmeinke** [comment]
What do you mean?

**Comment by Noiwex** [comment]
Do you still support this project?

**Comment by colinmeinke** [comment]
What kind of support are you expecting?

**Comment by Noiwex** [comment]
Are you planning on continuing work on this project? It's in the awesome redux list https://github.com/xgrommx/awesome-redux
