### ISSUE TITLE
Add example of page title / meta data updating

### ISSUE THREAD

**Issue by colinmeinke** [colinmeinke/universal-js#8]

**Comment by felixsanz** [comment]
Would you accept a PR for https://github.com/nfl/react-helmet ?

**Comment by colinmeinke** [comment]
No, as I'm planning on adding head data to my router http://www.colinmeinke.com/post/rethinking-routes. I think routing is where that belongs.

**Comment by felixsanz** [comment]
But what about dynamic data? For example, in a page with pagination, you would need to add `<link rel="prev" />` and `<link rel="next" />`, or even `<meta name="description" content"_description_of_a_blog_post />`.

Those depend on data that is gathered in the component, for example, via api call in `componentWillMount`. You usually **don't have that kind of data inside the router.**

I don't understand 100% your `onEnter` inside your blog post, maybe you are fetching the component first, then updating meta, and then showing component lazily, but definitely **is the page the one that sets the `head` data, not the router.**

In a MVC classic style, the router just route the url into the proper **controller**, and it's the job of the **controller** to prepare the data for the `<head>` tag, and pass the values to the **view** (usually template), so the `<head>` is updated there.

I mean, i think is a bad idea that the router manage data, even if it's `head` data. It's job is just routing requests to proper handlers.

In react-helmet, you add the `helmet` component to your component. So it's like the component is setting the head data, not the router.

What do you think?
